# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a210fb57d0ed9c3747b603c3e9629c9efdc7d03a9fb010a79dbf9ecb8c007e81ac1d1ef0628ea2299cc6201eef9a39a6ace2a45781d6b04ea2960ff4782c476

test:
  secret_key_base: ecf3d075610a40f1a1b504281a95beb1c9b553fafdcf600a0d3c395da377e0171ff661c416ed07168583734da706c2615c70a9348f06e457b93e18bad351b687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
